name: Precheckin
on:
  pull_request_target:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pip install -r dev.txt
      - run: npm install
      - run: make format
      - run: git diff --exit-code

  unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r dev.txt
      - run: make tests

  integration-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}
      - run: make image
      - run: make up
      - run: make integration-tests
      - run: make down
